# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['run_gui.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/pktmask/resources/log_template.html', 'resources'),
        ('src/pktmask/resources/summary.md', 'resources'),
        ('src/pktmask/resources/config_template.yaml', 'resources'),
    ],
    hiddenimports=[
        'markdown',
        'markdown.extensions',
        'markdown.preprocessors',
        'markdown.postprocessors',
        'markdown.blockprocessors',
        'markdown.inlinepatterns',
        'markdown.treeprocessors',
        'markdown.util',
        'pydantic',
        'pydantic.fields',
        'pydantic.main',
        'pydantic.typing',
        'pydantic.validators',
        'pydantic._internal',
        'pydantic.config',
        'pydantic.dataclasses',
        'pydantic.json_schema',
        'pydantic.types',
        'pydantic.networks',
        'pydantic.color',
        'yaml',
        'yaml.loader',
        'yaml.dumper',
        'yaml.representer',
        'yaml.resolver',
        'yaml.constructor',
        'yaml.composer',
        'yaml.scanner',
        'yaml.parser',
        'yaml.emitter',
        'yaml.serializer',
        'typing_extensions',
        'annotated_types'
    ],
    hookspath=['hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PktMask',
    icon='assets/PktMask.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PktMask',
)
app = BUNDLE(
    coll,
    name='PktMask.app',
    icon='assets/PktMask.icns',
    bundle_identifier=None,
)