# PktMask 测试配置文件
# 用于定制自动化测试套件的行为

# 测试套件配置
test_suites:
  # 单元测试配置
  unit:
    enabled: true
    timeout: 300  # 5分钟超时
    paths:
      - "tests/test_basic_phase_7.py"
      - "tests/test_config_system.py"
      - "tests/test_algorithm_plugins.py"
      - "tests/test_managers.py"
      - "tests/test_pktmask.py"
      - "tests/test_gui.py"
      - "tests/test_core_ip_processor_unit.py"
    pytest_args:
      - "--verbose"
      - "--tb=short"
      - "--durations=10"
  
  # 集成测试配置
  integration:
    enabled: true
    timeout: 600  # 10分钟超时
    paths:
      - "tests/test_integration_phase_7.py"
      - "test_phase_6_4_basic.py"
      - "test_plugin_system.py"
      - "test_enhanced_plugin_system.py"
    pytest_args:
      - "--verbose"
      - "--tb=short"
  
  # 性能测试配置
  performance:
    enabled: true
    timeout: 1200  # 20分钟超时
    paths:
      - "tests/performance/test_runner.py"
      - "tests/performance/benchmark_suite.py"
      - "tests/performance/run_optimization_test.py"
    standalone: true  # 使用独立运行模式
  
  # 阶段特定测试配置
  phase_specific:
    enabled: true
    timeout: 900  # 15分钟超时
    paths:
      - "test_phase_6_2_optimized_plugins.py"
      - "test_phase_6_2_enhanced_plugins.py"
      - "test_phase_6_3_algorithm_configs.py"
      - "test_phase_6_4_dynamic_loading.py"
    standalone: true

# 覆盖率配置
coverage:
  enabled: true
  min_coverage: 80  # 最低覆盖率要求
  source_dirs:
    - "src/pktmask"
  exclude_patterns:
    - "*/tests/*"
    - "*/test_*.py"
    - "*/__pycache__/*"
    - "*/migrations/*"
  formats:
    - "html"
    - "json"
    - "term"

# 报告配置
reporting:
  output_dir: "test_reports"
  formats:
    - "html"
    - "json"
    - "junit"
  auto_open: true  # 自动打开HTML报告
  retention_days: 30  # 报告保留天数
  
# CI/CD配置
ci:
  # 失败时的行为
  fail_fast: false  # 不在第一个失败时停止
  # 重试配置
  retry:
    enabled: true
    max_attempts: 2
    delay_seconds: 5
  # 并行配置
  parallel:
    enabled: false  # 暂时禁用并行测试
    max_workers: 4

# 环境检查配置
environment:
  python_version:
    min: "3.8"
    max: "3.12"
  required_packages:
    - "pytest"
    - "pytest-cov"
    - "pytest-html"
    - "pydantic"
    - "scapy"
    - "PyQt6"
  memory:
    min_mb: 1024  # 最少1GB内存
  disk:
    min_mb: 500   # 最少500MB磁盘空间

# 通知配置
notifications:
  # 邮件通知 (可选)
  email:
    enabled: false
    smtp_server: ""
    recipients: []
  # Webhook通知 (可选)
  webhook:
    enabled: false
    url: ""
    headers: {}

# 测试数据配置
test_data:
  # 测试文件路径
  sample_pcap: "tests/data/sample.pcap"
  large_pcap: "tests/data/large_sample.pcap"
  # 临时目录配置
  temp_dir: "temp_test_data"
  cleanup_after_test: true

# 性能基准配置
performance_benchmarks:
  ip_anonymization:
    min_throughput: 1000  # packets/sec
    max_memory_mb: 100
  deduplication:
    min_throughput: 500   # packets/sec
    max_memory_mb: 50
  packet_processing:
    min_throughput: 2000  # packets/sec
    max_memory_mb: 150

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "test_suite.log"
  max_size_mb: 10
  backup_count: 5 