# 场景3：TLS应用数据包测试
# 目标：验证对TLS ApplicationData包的掩码处理 - 这是主要的测试目标

metadata:
  name: "TLS应用数据包测试"
  description: "验证对TLS ApplicationData包(包14和包15)的掩码处理，只保留TLS记录头"
  expected_modified_packets: 2
  expected_masked_bytes: 306   # (205-5) + (111-5) = 200 + 106
  expected_kept_bytes: 10      # 5 + 5
  test_type: "tls_application_data"

keep_range_rules:
  # TLS ApplicationData包（包14 - 客户端发送）
  - stream_id: "TCP_10.171.250.80:33492_10.50.50.161:443_forward"
    sequence_start: 2422050425
    sequence_end: 2422050630    # 2422050425 + 205 (载荷长度)
    keep_ranges:
      - [0, 5]   # 只保留TLS记录头，应用数据完全掩码
    protocol_hint: "TLS"
  
  # TLS ApplicationData包（包15 - 服务端响应）
  - stream_id: "TCP_10.171.250.80:33492_10.50.50.161:443_reverse"
    sequence_start: 3913404815
    sequence_end: 3913404926    # 3913404815 + 111 (载荷长度)
    keep_ranges:
      - [0, 5]   # 只保留TLS记录头，应用数据完全掩码
    protocol_hint: "TLS"

verification:
  target_packets: [14, 15]  # 只有包14和包15应该被修改
  unchanged_packets: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22]
  modified_payload_check:
    packet_14:
      bytes_0_to_4: "unchanged"    # TLS记录头保持不变 (17 03 03 00 a9)
      bytes_5_to_204: "masked"     # 应用数据完全掩码
      original_preview: "17030300a91b955d6156ef5b870467a7"
      expected_preview: "17030300a900000000000000000000000"
    packet_15:
      bytes_0_to_4: "unchanged"    # TLS记录头保持不变 (17 03 03 00 6a)
      bytes_5_to_110: "masked"     # 应用数据完全掩码
      original_preview: "170303006a0000000000000001731224"
      expected_preview: "170303006a0000000000000000000000"

critical_test:
  importance: "HIGH"
  reason: "ApplicationData包是载荷掩码的主要目标，验证敏感应用数据是否被正确掩码" 