# PktMask 配置模板
# 版本: 1.0

# 配置版本号
config_version: "1.0"

# 用户界面配置
ui:
  # 窗口设置
  window_width: 1200          # 窗口宽度
  window_height: 800          # 窗口高度
  window_min_width: 800       # 最小窗口宽度
  window_min_height: 600      # 最小窗口高度
  
  # 主题和外观
  theme: "auto"               # 主题模式: auto, light, dark
  language: "zh_CN"           # 界面语言: zh_CN, en_US
  font_size: 12               # 字体大小 (8-24)
  
  # 默认选项
  default_dedup: true         # 默认启用去重
  default_mask_ip: true       # 默认启用IP匿名化
  default_mask: true          # 默认启用载荷掩码
  
  # 界面行为
  remember_last_dir: true     # 记住上次使用的目录
  auto_open_output: false     # 处理完成后自动打开输出目录
  show_progress_details: true # 显示详细进度信息

# 处理过程配置
processing:
  # 算法参数
  chunk_size: 10              # 数据包处理块大小 (1-1000)
  max_retry_attempts: 3       # 最大重试次数 (1-10)
  timeout_seconds: 300        # 处理超时时间(秒) (60-3600)
  
  # IP匿名化设置
  anonymization_strategy: "hierarchical"  # 匿名化策略: hierarchical, random, cryptographic
  preserve_subnet_structure: true         # 保持子网结构
  consistent_mapping: true                # 保持一致性映射
  
  # 去重设置
  dedup_algorithm: "hash_based"           # 去重算法: hash_based, content_based, hybrid
  dedup_threshold: 0.95                   # 去重相似度阈值 (0.0-1.0)
  
  # 掩码设置
  mask_mode: "enhanced"                   # 掩码模式: enhanced(智能协议分析), basic(透传)
  preserve_tls_handshake: true            # 保留TLS握手数据
  preserve_tls_alerts: true               # 保留TLS告警数据
  tls_header_preserve_bytes: 5            # TLS头部保留字节数

# 性能配置
performance:
  # 并发设置
  max_workers: 4              # 最大工作线程数 (1-16)
  use_multiprocessing: false  # 使用多进程处理
  memory_limit_mb: 1024       # 内存限制(MB) (256-8192)
  
  # 缓存设置
  enable_caching: true        # 启用缓存
  cache_size_mb: 256          # 缓存大小(MB) (64-2048)
  cache_cleanup_interval: 300 # 缓存清理间隔(秒) (60-3600)
  
  # 进度报告
  progress_update_interval: 100  # 进度更新间隔(包数) (10-10000)
  enable_detailed_stats: true    # 启用详细统计

# 文件处理配置
file:
  # 目录设置
  default_input_dir: null     # 默认输入目录 (null表示无默认值)
  default_output_dir: null    # 默认输出目录 (null表示无默认值)
  output_dir_pattern: "{input_dir_name}-Masked-{timestamp}"  # 输出目录命名模式
  
  # 文件大小限制
  max_file_size_gb: 2.0       # 最大文件大小(GB) (0.1-100.0)
  min_file_size_bytes: 24     # 最小文件大小(字节) (1-1024)
  
  # 支持的文件类型
  supported_extensions:       # 支持的文件扩展名
    - ".pcap"
    - ".pcapng"
  
  # 输出设置
  preserve_timestamps: true   # 保留文件时间戳
  create_backup: false        # 创建原文件备份
  cleanup_temp_files: true    # 自动清理临时文件
  
  # 报告设置
  generate_html_report: true  # 生成HTML报告
  generate_json_report: true  # 生成JSON报告
  include_detailed_stats: true # 包含详细统计信息

# 日志配置
logging:
  # 日志级别
  console_level: "INFO"       # 控制台日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_level: "DEBUG"         # 文件日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL

  # 日志文件设置
  log_file_path: null         # 日志文件路径 (null表示使用默认路径)
  max_log_size_mb: 10         # 最大日志文件大小(MB) (1-100)
  log_backup_count: 5         # 日志备份文件数量 (1-20)

  # 日志格式
  include_timestamp: true     # 包含时间戳
  include_module_name: true   # 包含模块名
  include_line_number: false  # 包含行号

  # 详细日志控制
  enable_protocol_parsing_logs: false  # 启用协议栈解析详细日志 (调试用)

# 元数据 (自动生成，请勿手动修改)
created_at: null
updated_at: null 