# Naming alias mapping configuration
# Records formal mapping relationships between domain models and processing logic
#
# Version: 2.0 (Updated for StageBase architecture)
# Last Updated: 2025-07-25
#
# Note: Historical aliases have been removed as part of the StageBase architecture
# migration. Only current standard naming conventions are maintained.

# Result type mapping (current standard naming only)
result_type_mapping:
  # Deduplication related
  remove_dupes: "DeduplicationResult"

  # IP anonymization related
  anonymize_ips: "IPAnonymizationResult"

  # Payload masking related
  mask_payloads: "MaskingResult"

# Step name mapping (updated for StageBase architecture)
step_name_mapping:
  # Standardized step names
  deduplication:
    aliases: ["remove_dupes"]  # Current standard naming
    canonical: "Remove Dupes"
    description: "Packet deduplication processing"

  ip_anonymization:
    aliases: ["anonymize_ips"]  # Current standard naming
    canonical: "Anonymize IPs"
    description: "IP address anonymization processing"

  payload_masking:
    aliases: ["mask_payloads"]  # Current standard naming
    canonical: "Mask Payloads"
    description: "Payload masking processing"

# Processor type mapping (deprecated - using StageBase architecture)
# processor_type_mapping:
#   # Deduplication processor
#   dedup:
#     class_name: "DeduplicationProcessor"
#     legacy_aliases: ["Deduplicator"]
#
#   # IP anonymization processor
#   anon:
#     class_name: "IPAnonymizationProcessor"
#     legacy_aliases: ["IPAnonymizer"]
#
#   # Payload masking processor
#   mask:
#     class_name: "MaskingProcessor"
#     legacy_aliases: ["MaskProcessor"]

# Stage type mapping (StageBase architecture - current implementation)
stage_type_mapping:
  # Deduplication Stage
  dedup:
    class_name: "DeduplicationStage"
    description: "Unified deduplication processing stage"

  # IP Anonymization Stage
  anon:
    class_name: "AnonymizationStage"
    description: "Unified IP anonymization processing stage"

  # Payload Masking Stage
  mask:
    class_name: "MaskingStage"
    description: "Unified payload masking processing stage"

# Configuration key mapping (using standard GUI naming)
config_key_mapping:
  # Pipeline configuration keys
  remove_dupes:
    description: "Remove Dupes configuration"
    enabled_key: "enabled"

  anonymize_ips:
    description: "Anonymize IPs configuration"
    enabled_key: "enabled"
    strategy_key: "strategy"

  mask_payloads:
    description: "Mask Payloads configuration"
    enabled_key: "enabled"
    mode_key: "mode"

# File suffix mapping (using standard naming)
file_suffix_mapping:
  remove_dupes: "-RemoveDupes"
  anonymize_ips: "-AnonymizeIPs"
  mask_payloads: "-MaskPayloads"
