# Naming alias mapping configuration
# Records formal mapping relationships between domain models and processing logic

# Result type mapping
result_type_mapping:
  # Deduplication related
  dedup_packet: "DeduplicationResult"
  remove_dupes: "DeduplicationResult"

  # IP anonymization related
  anonymize_ips: "IPAnonymizationResult"

  # Payload masking related
  mask_payloads: "MaskingResult"
  mask_payload: "MaskingResult"

# Step name mapping
step_name_mapping:
  # Standardized step names
  deduplication:
    aliases: ["remove_dupes", "dedup_packet", "dedup"]
    canonical: "Deduplication"
    description: "Packet deduplication processing"

  ip_anonymization:
    aliases: ["anon_ip", "anonymize_ips"]
    canonical: "IP Anonymization"
    description: "IP address anonymization processing"

  payload_masking:
    aliases: ["mask_payload", "mask_payloads"]
    canonical: "Payload Masking"
    description: "Payload masking processing"

# 处理器类型mapping
processor_type_mapping:
  # 去重处理器
  dedup:
    class_name: "DeduplicationProcessor"
    legacy_aliases: ["Deduplicator"]
    
  # IP匿名化处理器
  anon:
    class_name: "IPAnonymizationProcessor" 
    legacy_aliases: ["IPAnonymizer"]
    
  # 载荷掩码处理器
  mask:
    class_name: "MaskingProcessor"
    legacy_aliases: ["MaskProcessor"]

# Stage类型mapping
stage_type_mapping:
  # 去重Stage
  dedup:
    class_name: "DeduplicationStage"
    legacy_aliases: ["DedupStage"]
    
  # IP匿名化Stage
  anon:
    class_name: "AnonStage"
    legacy_aliases: ["IPAnonymizationStage"]
    
  # 载荷掩码Stage
  mask:
    class_name: "MaskStage"
    legacy_aliases: ["MaskPayloadStage"]

# 配置键mapping（使用标准GUI命名）
config_key_mapping:
  # Pipeline配置键
  remove_dupes:
    description: "Remove Dupes 配置"
    enabled_key: "enabled"

  anonymize_ips:
    description: "Anonymize IPs 配置"
    enabled_key: "enabled"
    strategy_key: "strategy"

  mask_payloads:
    description: "Mask Payloads 配置"
    enabled_key: "enabled"
    mode_key: "mode"

# 文件后缀mapping（使用标准命名）
file_suffix_mapping:
  remove_dupes: "-RemoveDupes"
  anonymize_ips: "-AnonymizeIPs"
  mask_payloads: "-MaskPayloads"
