# PktMask Configuration Template
# Version: 1.0

# Configuration version
config_version: "1.0"

# User interface configuration
ui:
  # Window settings
  window_width: 1200          # Window width
  window_height: 800          # Window height
  window_min_width: 800       # Minimum window width
  window_min_height: 600      # Minimum window height

  # Theme and appearance
  theme: "auto"               # Theme mode: auto, light, dark
  language: "en_US"           # Interface language: zh_CN, en_US
  font_size: 12               # Font size (8-24)

  # Default options (using standard GUI naming)
  default_remove_dupes: true  # Default enable Remove Dupes
  default_anonymize_ips: true # Default enable Anonymize IPs
  default_mask_payloads: true # Default enable Mask Payloads

  # Interface behavior
  remember_last_dir: true     # Remember last used directory
  auto_open_output: false     # Auto open output directory after processing
  show_progress_details: true # Show detailed progress information

# 处理过程配置
processing:
  # 算法参数
  chunk_size: 10              # 数据包处理块大小 (1-1000)
  max_retry_attempts: 3       # 最大重试次数 (1-10)
  timeout_seconds: 300        # 处理超时时间(秒) (60-3600)
  
  # Anonymize IPs 设置 (UnifiedIPAnonymizationStage)
  anonymization_strategy: "hierarchical"  # 匿名化策略: hierarchical, random, cryptographic
  preserve_subnet_structure: true         # 保持子网结构
  consistent_mapping: true                # 保持一致性映射

  # Remove Dupes 设置 (UnifiedDeduplicationStage)
  dedup_algorithm: "hash_based"           # 去重算法: hash_based, content_based, hybrid
  dedup_threshold: 0.95                   # 去重相似度阈值 (0.0-1.0)

  # Mask Payloads 设置
  preserve_tls_handshake: true            # 保留TLS握手数据
  preserve_tls_alerts: true               # 保留TLS告警数据
  tls_header_preserve_bytes: 5            # TLS头部保留字节数

# 性能配置
performance:
  # 并发设置
  max_workers: 4              # 最大工作线程数 (1-16)
  use_multiprocessing: false  # 使用多进程处理
  memory_limit_mb: 1024       # 内存限制(MB) (256-8192)
  
  # 缓存设置
  enable_caching: true        # 启用缓存
  cache_size_mb: 256          # 缓存大小(MB) (64-2048)
  cache_cleanup_interval: 300 # 缓存清理间隔(秒) (60-3600)
  
  # 进度报告
  progress_update_interval: 100  # Progress update interval (packet count) (10-10000)
  enable_detailed_stats: true    # Enable detailed statistics

# File processing configuration
file:
  # Directory settings
  default_input_dir: null     # Default input directory (null means no default)
  default_output_dir: null    # Default output directory (null means no default)
  output_dir_pattern: "{input_dir_name}-Masked-{timestamp}"  # Output directory naming pattern

  # File size limits
  max_file_size_gb: 2.0       # Maximum file size (GB) (0.1-100.0)
  min_file_size_bytes: 24     # Minimum file size (bytes) (1-1024)

  # Supported file types
  supported_extensions:       # Supported file extensions
    - ".pcap"
    - ".pcapng"

  # Output settings
  preserve_timestamps: true   # Preserve file timestamps
  create_backup: false        # Create original file backup
  cleanup_temp_files: true    # Auto cleanup temporary files

  # Report settings
  generate_html_report: true  # Generate HTML report
  generate_json_report: true  # Generate JSON report
  include_detailed_stats: true # Include detailed statistics

# Logging configuration
logging:
  # Log levels
  console_level: "INFO"       # Console log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_level: "DEBUG"         # File log level: DEBUG, INFO, WARNING, ERROR, CRITICAL

  # Log file settings
  log_file_path: null         # Log file path (null means use default path)
  max_log_size_mb: 10         # Maximum log file size (MB) (1-100)
  log_backup_count: 5         # Log backup file count (1-20)

  # Log format
  include_timestamp: true     # Include timestamp
  include_module_name: true   # Include module name
  include_line_number: false  # Include line number

  # Detailed log control
  enable_protocol_parsing_logs: false  # Enable protocol stack parsing detailed logs (for debugging)

# Metadata (auto-generated, do not modify manually)
created_at: null
updated_at: null